"""
Smart Parser - Runtime Data Extraction

Last Updated: 2025-12-20
Status: Active
Purpose: Extract data from websites using validated site dictionaries

Architecture:
- Load JSON site dictionary (generated by Scanner)
- Navigate to target pages
- Extract data using validated selectors
- Apply transformations (currency parsing, percentage, etc.)
- Return structured data (Pydantic models)

Self-Healing:
- If primary selector fails, try next selector in dictionary
- Log selector failures for re-scanning

File Size: <300 lines (compliant)
"""

import re
from datetime import datetime
from pathlib import Path
from typing import Dict, List, Optional, Any

from playwright.async_api import async_playwright, Browser, Page

from app.core.logging_config import get_logger
from app.models.cartographer import SiteDictionary, DataType
from app.services.cartographer.smart_parser import SmartParser as TypeCaster

logger = get_logger(__name__)


class SmartParser:
    """
    Runtime data extractor using validated site dictionaries.
    
    Workflow:
    1. Load site dictionary (JSON)
    2. For each URL to scrape:
       - Identify template by URL pattern
       - Navigate to page
       - Execute interceptors
       - For each region:
         - Locate container
         - Extract fields using validated selectors
         - Apply transformations
    3. Return structured data
    """

    def __init__(self, dictionary_path: Path):
        """
        Initialize parser with site dictionary.
        
        Args:
            dictionary_path: Path to JSON site dictionary
        """
        self.dictionary_path = dictionary_path
        self.dictionary: Optional[SiteDictionary] = None
        self.browser: Optional[Browser] = None

    def load_dictionary(self) -> SiteDictionary:
        """
        Load and validate site dictionary.
        
        Returns:
            SiteDictionary object
            
        Raises:
            FileNotFoundError: If dictionary file doesn't exist
            ValueError: If JSON is invalid
        """
        logger.info("Loading dictionary", extra={"path": str(self.dictionary_path)})

        if not self.dictionary_path.exists():
            raise FileNotFoundError(f"Dictionary not found: {self.dictionary_path}")

        import json
        with open(self.dictionary_path, "r") as f:
            raw_dict = json.load(f)

        try:
            self.dictionary = SiteDictionary(**raw_dict)
            logger.info(
                "Dictionary loaded",
                extra={
                    "site": self.dictionary.site_name,
                    "templates": len(self.dictionary.templates),
                },
            )
            return self.dictionary
        except Exception as e:
            logger.error(
                "Dictionary validation failed",
                extra={"error": str(e)},
                exc_info=True,
            )
            raise ValueError(f"Invalid dictionary: {e}")

    async def _launch_browser(self) -> Browser:
        """Launch Playwright browser."""
        logger.info("Launching browser")
        playwright = await async_playwright().start()
        self.browser = await playwright.chromium.launch(headless=True)
        return self.browser

    def _identify_template(self, url: str) -> Optional[Dict]:
        """
        Identify template by URL pattern matching.
        
        Args:
            url: Target URL
            
        Returns:
            Template dictionary or None
        """
        for template in self.dictionary.templates:
            pattern = template["url_pattern"]
            if re.search(pattern, url):
                logger.info(
                    "Template identified",
                    extra={"template": template["template_name"], "url": url},
                )
                return template

        logger.warning("No template matched URL", extra={"url": url})
        return None

    def _transform_value(self, raw_value: str, data_type: str) -> Any:
        """
        Apply data type transformations using SmartParser module.
        
        Args:
            raw_value: Raw text extracted from page
            data_type: Target data type (currency, percentage, float, int, list, etc.)
            
        Returns:
            Transformed value
        """
        if not raw_value or raw_value == "-":
            return None

        raw_value = raw_value.strip()

        try:
            # Map string data_type to DataType enum
            type_mapping = {
                "currency": DataType.CURRENCY,
                "percentage": DataType.PERCENTAGE,
                "float": DataType.FLOAT,
                "int": DataType.INTEGER,
                "integer": DataType.INTEGER,
                "list": DataType.LIST,
                "string": DataType.STRING,
            }
            
            dtype = type_mapping.get(data_type.lower(), DataType.STRING)
            
            # Delegate to TypeCaster (SmartParser module)
            return TypeCaster.parse(raw_value, dtype)

        except Exception as e:
            logger.warning(
                "Transformation failed, returning raw value",
                extra={"raw": raw_value, "type": data_type, "error": str(e)},
            )
            return raw_value  # Return raw value on failure

    async def extract_data(self, url: str) -> Dict[str, Any]:
        """
        Extract structured data from URL.
        
        Args:
            url: Target URL to scrape
            
        Returns:
            Extracted data dictionary with regions
            
        Raises:
            ValueError: If no template matches URL
        """
        logger.info("Extracting data", extra={"url": url})

        if not self.dictionary:
            self.load_dictionary()

        # Identify template
        template = self._identify_template(url)
        if not template:
            raise ValueError(f"No template for URL: {url}")

        if not self.browser:
            await self._launch_browser()

        page = await self.browser.new_page()
        try:
            # Navigate to page
            await page.goto(url, wait_until="networkidle")
            logger.info("Page loaded", extra={"url": url})

            # Extract data from all regions
            extracted_data = {
                "url": url,
                "template": template["template_name"],
                "extracted_at": datetime.utcnow().isoformat(),
                "regions": {},
            }

            for region in template["regions"]:
                region_id = region["region_id"]
                region_data = {}

                for rule in region["parsing_rules"]:
                    field_name = rule["field_name"]
                    selector = rule.get("selector")

                    # Skip if selector failed validation
                    if not selector or not rule.get("valid", False):
                        logger.warning(
                            "Skipping invalid field",
                            extra={"field": field_name, "region": region_id},
                        )
                        region_data[field_name] = None
                        continue

                    try:
                        # Extract text
                        element = await page.query_selector(selector)
                        if element:
                            raw_text = await element.inner_text()
                            raw_text = raw_text.strip()

                            # Apply transformation
                            transformed = self._transform_value(
                                raw_text, rule.get("data_type", "string")
                            )
                            region_data[field_name] = transformed

                            logger.debug(
                                "Field extracted",
                                extra={
                                    "field": field_name,
                                    "raw": raw_text,
                                    "transformed": transformed,
                                },
                            )
                        else:
                            logger.warning(
                                "Element not found",
                                extra={"field": field_name, "selector": selector},
                            )
                            region_data[field_name] = None

                    except Exception as e:
                        logger.error(
                            "Field extraction failed",
                            extra={"field": field_name, "error": str(e)},
                            exc_info=True,
                        )
                        region_data[field_name] = None

                extracted_data["regions"][region_id] = region_data

            logger.info(
                "Data extraction complete",
                extra={
                    "url": url,
                    "regions": len(extracted_data["regions"]),
                },
            )

            return extracted_data

        except Exception as e:
            logger.error(
                "Extraction failed",
                extra={"url": url, "error": str(e)},
                exc_info=True,
            )
            raise
        finally:
            await page.close()

    async def close(self):
        """Close browser and cleanup."""
        if self.browser:
            await self.browser.close()
            logger.info("Browser closed")
