"""
Smart Parser - Runtime Data Extraction

Last Updated: 2025-12-20
Status: Active
Purpose: Extract data from websites using validated site dictionaries

Architecture:
- Load JSON site dictionary (generated by Scanner)
- Navigate to target pages
- Extract data using validated selectors
- Apply transformations (currency parsing, percentage, etc.)
- Return structured data (Pydantic models)

Self-Healing:
- If primary selector fails, try next selector in dictionary
- Log selector failures for re-scanning

File Size: <300 lines (compliant)
"""

import re
from datetime import datetime
from pathlib import Path
from typing import Dict, List, Optional, Any

from playwright.async_api import async_playwright, Browser, Page

from app.core.logging_config import get_logger
from app.models.cartographer import SiteDictionary

logger = get_logger(__name__)


class SmartParser:
    """
    Runtime data extractor using validated site dictionaries.
    
    Workflow:
    1. Load site dictionary (JSON)
    2. For each URL to scrape:
       - Identify template by URL pattern
       - Navigate to page
       - Execute interceptors
       - For each region:
         - Locate container
         - Extract fields using validated selectors
         - Apply transformations
    3. Return structured data
    """

    def __init__(self, dictionary_path: Path):
        """
        Initialize parser with site dictionary.
        
        Args:
            dictionary_path: Path to JSON site dictionary
        """
        self.dictionary_path = dictionary_path
        self.dictionary: Optional[SiteDictionary] = None
        self.browser: Optional[Browser] = None

    def load_dictionary(self) -> SiteDictionary:
        """
        Load and validate site dictionary.
        
        Returns:
            SiteDictionary object
            
        Raises:
            FileNotFoundError: If dictionary file doesn't exist
            ValueError: If JSON is invalid
        """
        logger.info("Loading dictionary", extra={"path": str(self.dictionary_path)})

        if not self.dictionary_path.exists():
            raise FileNotFoundError(f"Dictionary not found: {self.dictionary_path}")

        import json
        with open(self.dictionary_path, "r") as f:
            raw_dict = json.load(f)

        try:
            self.dictionary = SiteDictionary(**raw_dict)
            logger.info(
                "Dictionary loaded",
                extra={
                    "site": self.dictionary.site_name,
                    "templates": len(self.dictionary.templates),
                },
            )
            return self.dictionary
        except Exception as e:
            logger.error(
                "Dictionary validation failed",
                extra={"error": str(e)},
                exc_info=True,
            )
            raise ValueError(f"Invalid dictionary: {e}")

    async def _launch_browser(self) -> Browser:
        """Launch Playwright browser."""
        logger.info("Launching browser")
        playwright = await async_playwright().start()
        self.browser = await playwright.chromium.launch(headless=True)
        return self.browser

    def _identify_template(self, url: str) -> Optional[Dict]:
        """
        Identify template by URL pattern matching.
        
        Args:
            url: Target URL
            
        Returns:
            Template dictionary or None
        """
        for template in self.dictionary.templates:
            pattern = template["url_pattern"]
            if re.search(pattern, url):
                logger.info(
                    "Template identified",
                    extra={"template": template["template_name"], "url": url},
                )
                return template

        logger.warning("No template matched URL", extra={"url": url})
        return None

    def _transform_value(self, raw_value: str, data_type: str) -> Any:
        """
        Apply data type transformations.
        
        Args:
            raw_value: Raw text extracted from page
            data_type: Target data type (currency, percentage, float, int, list)
            
        Returns:
            Transformed value
        """
        if not raw_value or raw_value == "-":
            return None

        raw_value = raw_value.strip()

        try:
            if data_type == "currency":
                # "$1.5B" → 1500000000
                # "$450.00" → 450.0
                return self._parse_currency(raw_value)

            elif data_type == "percentage":
                # "12.5%" → 12.5
                return self._parse_percentage(raw_value)

            elif data_type == "float":
                # "45.23" → 45.23
                return float(raw_value.replace(",", ""))

            elif data_type == "int":
                # "1,234" → 1234
                return int(raw_value.replace(",", ""))

            elif data_type == "list":
                # "AAPL MSFT GOOGL" → ["AAPL", "MSFT", "GOOGL"]
                return [item.strip() for item in raw_value.split() if item.strip()]

            else:  # string (default)
                return raw_value

        except Exception as e:
            logger.warning(
                "Transformation failed",
                extra={"raw": raw_value, "type": data_type, "error": str(e)},
            )
            return raw_value  # Return raw value on failure

    def _parse_currency(self, value: str) -> Optional[float]:
        """
        Parse currency with suffix (K, M, B, T).
        
        Examples:
            "$1.5B" → 1500000000.0
            "$450.00" → 450.0
            "2.77T" → 2770000000000.0
        """
        # Remove currency symbols and spaces
        value = re.sub(r'[$€£¥,\s]', '', value)

        # Extract numeric part and suffix
        match = re.match(r'^([\d.]+)([KMBT])?$', value, re.IGNORECASE)
        if not match:
            return None

        number = float(match.group(1))
        suffix = match.group(2)

        # Apply multiplier
        multipliers = {
            'K': 1_000,
            'M': 1_000_000,
            'B': 1_000_000_000,
            'T': 1_000_000_000_000,
        }

        if suffix:
            number *= multipliers[suffix.upper()]

        return number

    def _parse_percentage(self, value: str) -> Optional[float]:
        """
        Parse percentage value.
        
        Examples:
            "12.5%" → 12.5
            "-3.27%" → -3.27
        """
        match = re.match(r'^([-+]?[\d.]+)%?$', value.replace(',', ''))
        if match:
            return float(match.group(1))
        return None

    async def extract_data(self, url: str) -> Dict[str, Any]:
        """
        Extract structured data from URL.
        
        Args:
            url: Target URL to scrape
            
        Returns:
            Extracted data dictionary with regions
            
        Raises:
            ValueError: If no template matches URL
        """
        logger.info("Extracting data", extra={"url": url})

        if not self.dictionary:
            self.load_dictionary()

        # Identify template
        template = self._identify_template(url)
        if not template:
            raise ValueError(f"No template for URL: {url}")

        if not self.browser:
            await self._launch_browser()

        page = await self.browser.new_page()
        try:
            # Navigate to page
            await page.goto(url, wait_until="networkidle")
            logger.info("Page loaded", extra={"url": url})

            # Extract data from all regions
            extracted_data = {
                "url": url,
                "template": template["template_name"],
                "extracted_at": datetime.utcnow().isoformat(),
                "regions": {},
            }

            for region in template["regions"]:
                region_id = region["region_id"]
                region_data = {}

                for rule in region["parsing_rules"]:
                    field_name = rule["field_name"]
                    selector = rule.get("selector")

                    # Skip if selector failed validation
                    if not selector or not rule.get("valid", False):
                        logger.warning(
                            "Skipping invalid field",
                            extra={"field": field_name, "region": region_id},
                        )
                        region_data[field_name] = None
                        continue

                    try:
                        # Extract text
                        element = await page.query_selector(selector)
                        if element:
                            raw_text = await element.inner_text()
                            raw_text = raw_text.strip()

                            # Apply transformation
                            transformed = self._transform_value(
                                raw_text, rule.get("data_type", "string")
                            )
                            region_data[field_name] = transformed

                            logger.debug(
                                "Field extracted",
                                extra={
                                    "field": field_name,
                                    "raw": raw_text,
                                    "transformed": transformed,
                                },
                            )
                        else:
                            logger.warning(
                                "Element not found",
                                extra={"field": field_name, "selector": selector},
                            )
                            region_data[field_name] = None

                    except Exception as e:
                        logger.error(
                            "Field extraction failed",
                            extra={"field": field_name, "error": str(e)},
                            exc_info=True,
                        )
                        region_data[field_name] = None

                extracted_data["regions"][region_id] = region_data

            logger.info(
                "Data extraction complete",
                extra={
                    "url": url,
                    "regions": len(extracted_data["regions"]),
                },
            )

            return extracted_data

        except Exception as e:
            logger.error(
                "Extraction failed",
                extra={"url": url, "error": str(e)},
                exc_info=True,
            )
            raise
        finally:
            await page.close()

    async def close(self):
        """Close browser and cleanup."""
        if self.browser:
            await self.browser.close()
            logger.info("Browser closed")
